sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t frontend/docker-exercise -f Dockerfile.dev .

script :
  #- docker run frontend/docker-exercise npm run test -- --coverage
  - docker run -e CI=true frontend/docker-exercise npm run test